spring.application.name=customer-service
server.port=8081
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
